### ISSUE TITLE
考虑做成插件吗？

### ISSUE THREAD

**Issue by TinkMingKing** [suka233/siyuan-Kmind#10]
我觉得这种类型的更适合做插件，配合相关后端api，体验会更棒

**Comment by suka233** [comment]
目前有计划做kmind插件，但是可能跟你预期的不太一样，因为目前准备开发的kmind插件主要是为kmind挂件服务的，具体来说，是为挂件增加一些高级功能与全局配置，例如：
1.为kmind挂件里面插入的思源块超链接提供 [文档/块的悬浮预览](https://ld246.com/article/1677155669657#2-%E6%96%87%E6%A1%A3-%E5%9D%97%E7%9A%84%E6%82%AC%E6%B5%AE%E9%A2%84%E8%A7%88) 的能力
2.全局配置所有kmind挂件的默认设置，例如，新建kmind挂件，会自动选择已经在插件中配置好的布局，主题，样式等等。。

至于进度，我才刚刚拉了一些作者的插件源码研究，目前对于插件的开发毫无头绪~~

**Comment by TinkMingKing** [comment]
插件开发我觉得还是比较好上手的，qq折腾群1017854502，siyuan的插件开发者几乎都在里面，有问题随时可以讨论交流，在你之前有markmind插件，那样的交互模式可能更适合导图，可以参照一下，相关插件api不会使用的可以随时在群里交流，总会有人答疑解惑，哪怕是凌晨
