### ISSUE TITLE
快捷键好像不好使，都没反应

### ISSUE THREAD

**Issue by bin38121cn** [suka233/siyuan-Kmind#11]

**Comment by suka233** [comment]
先关闭然后再重新打开一下引入该挂件的页面试试呢

**Comment by bin38121cn** [comment]
我重新删除后，再新建挂件所有的快捷键恢复正常了。但是之前好像是按了什么整理布局的按钮，目前这个问题暂时未能复现，等下次复现后，我试一下你那个方法

**Comment by suka233** [comment]
> 我重新删除后，再新建挂件所有的快捷键恢复正常了。但是之前好像是按了什么整理布局的按钮，目前这个问题暂时未能复现，等下次复现后，我试一下你那个方法

下次导图快捷键失灵，还可以试试点击一下挂件外面，即思源的编辑区域，再点击挂件内部，一般即可恢复。

**Comment by bin38121cn** [comment]
好的
