### ISSUE TITLE
频繁切换主题有的主题会一个一个节点的渲染，而且位置有偏差，有的主题就快很多

### ISSUE THREAD

**Issue by flower-muxi** [suka233/siyuan-Kmind#12]
我也是跟着原版写了一版vue3的，我那边有这些问题，你这边好像也存在这个问题。这种的话该如何解决呢？已经去掉了动画而且设置主题改成了非响应式数据，感觉没有什么变化

**Comment by suka233** [comment]
你的new MindMap出来的组件实例是响应式的吗？如果是的话，改成非响应式的试试
目前我只发现如果组件实例是响应式的话，调用setLayout方法会导致导图很卡，而切换布局，内部就会调用这个方法，所以我写的这个插件暂时把切换布局的功能去掉了

**Comment by suka233** [comment]
我试了一下  ，导图实例改成非响应式后，切换主题不卡了，应该就是这个问题了
![kmindfix](https://github.com/suka233/siyuan-Kmind/assets/43712875/2c3d3995-9c3f-47d4-809d-ede2d0717baa)

可能有用的信息：
[我的相关代码片段](https://github.com/suka233/siyuan-Kmind/blob/dev/src/views/home/index.vue#L106C1-L106C1)

**Comment by flower-muxi** [comment]
可真是奇怪，我克隆你的，本地打开就没你这么丝滑

**Comment by suka233** [comment]
> 可真是奇怪，我克隆你的，本地打开就没你这么丝滑

因为线上代码不是最新的，还没有把实例改为非响应式对象，你可以手动改改你的项目试试

**Comment by suka233333** [comment]
> 可真是奇怪，我克隆你的，本地打开就没你这么丝滑

发布的最新版本，已经将实例改为非响应式对象了，很丝滑，你可以试试，还有一点要注意，mindmap.setFullData方法传入的数据，一定要是非响应式的，不然也会导致卡顿

**Comment by suka233** [comment]
> 可真是奇怪，我克隆你的，本地打开就没你这么丝滑

发布的最新版本，已经将实例改为非响应式对象了，很丝滑，你可以试试，还有一点要注意，mindmap.setFullData方法传入的数据，一定要是非响应式的，不然也会导致卡顿
