### ISSUE TITLE
编辑节点的快捷键F2太冷门

### ISSUE THREAD

**Issue by xsinbh** [suka233/siyuan-Kmind#15]
# 需求介绍
在xmind中，按空格`space`键即可编辑节点，且处于全选状态。

# 期待结果
简单的话，将快捷键F2改为空格键即可

更高一点的要求，在进入编辑节点时文本默认处于全选状态，像xmind那样

**Comment by xsinbh** [comment]
by the way，如果想设置鼠标光标进入画布时（未点击），滚动鼠标滚轮不会翻动画布，怎么在文件中修改？（硬代码修改，因为我想着鼠标滚动翻画布这个设定也很合理，所以我只想在我的个人设置这永久关掉它。变成可选设置的话可能工作量会大很多）

因为挂件嵌入在笔记中，翻笔记的时候鼠标很容易进入画布，然后就不翻笔记页面了变成翻画布了，很闹心

这算是第二个issue了

**Comment by suka233** [comment]
空格键进入编辑状态，并全选已经更新，等待思源集市拉取然后更新即可，大概一个多小时吧。等不及的话也可以直接在这个仓库的release下载v1.1.4压缩包，解压覆盖本地kmind挂件文件夹。

至于滚轮事件，这个我研究研究。。可以新开一个issue，这样方便追踪问题。
