### ISSUE TITLE
请问概要功能怎么使用？

### ISSUE THREAD

**Issue by pisceswb** [suka233/siyuan-Kmind#18]
概要功能是用于两个统计节点的总结吗？怎么用呢？只能这样
![image](https://github.com/suka233/siyuan-Kmind/assets/104658457/06c13afc-057b-42ea-b7d2-c6057b4056b2)

**Comment by suka233** [comment]
现在的概要由于数据结构的设计原因，暂时不是太好用，只能概要单个节点，不能跨节点概要，见谅。
如果需要概要多个节点，可以选中父节点，然后点击概要按钮
![image](https://github.com/suka233/siyuan-Kmind/assets/43712875/80a1a69f-ec09-4595-8242-5216bfadc3b7)

**Comment by pisceswb** [comment]
好的，希望后面能正常使用。很棒的插件，赞！
