### ISSUE TITLE
建议增加全屏按钮

### ISSUE THREAD

**Issue by jiaoting** [suka233/siyuan-Kmind#19]
目前电脑上可以右键全屏，但是在ipad和手机端，由于不方便右键，全屏查看导图会非常不方便，建议在缩小放大那里有一个全屏按钮（禅模式也可以在这里设置一个按钮）

**Comment by suka233** [comment]
移动端全屏有点问题 正在寻找解决方案

**Comment by suka233** [comment]
禅模式按钮已加  请更新最新版本
