### ISSUE TITLE
下载使用没有增加节点选项，至少加个右键的那个菜单栏吧

### ISSUE THREAD

**Issue by xiaobaixuejava** [suka233/siyuan-Kmind#2]

**Comment by xiaobaixuejava** [comment]
![image](https://user-images.githubusercontent.com/67936232/225311015-516680db-3196-4421-b08a-41ff0956295b.png)

**Comment by xiaobaixuejava** [comment]
你可以加下那个增加节点 ，搞2个图标，或者把右键菜单栏代码加上，或者也可以搞个快捷键来添加节点  麻烦大佬弄下了

**Comment by suka233** [comment]
基本操作和xmind类似 回车增加兄弟节点 tab键插入下级节点
带快捷键说明的版本已经推上去了  明早等集市自动更新我的仓库就能看到了

**Comment by suka233** [comment]
右键菜单明天搞搞  争取后天上吧  哈哈

**Comment by xiaobaixuejava** [comment]
谢谢大佬 备注能用 markdown是真心好

**Comment by suka233** [comment]
> 大佬 这插件有没有什么制作教程？ 我想把他源码打个完整版，感觉没有md 写备注不方便。。。

可以把原作者的库克隆下来，改一下他的版本的本地数据存储的方式到思源挂件的属性上，然后打包即可
