### ISSUE TITLE
通过快捷键新增同级节点后，无法在新增的节点输入字符

### ISSUE THREAD

**Issue by primejava** [suka233/siyuan-Kmind#22]
如题，必须手动再点击一下新节点，才可以继续打字。
另外，在pdf上添加了一个标注，把这个标注的连接添加到导图的超链接上，无法进行跳转，默认跳到了浏览器上。
感谢大佬

**Comment by suka233** [comment]
第一个问题，按理来说是新增节点后会自动进入编辑模式，我没有复现这个问题。
第二个问题，请发一下标注的链接格式

**Comment by suka233** [comment]
请更新最新版本，还有问题请新开issue
