### ISSUE TITLE
请教节点字体不同问题

### ISSUE THREAD

**Issue by woniuxia** [suka233/siyuan-Kmind#23]
大佬好，感谢提供这么好用的挂件。
在使用过程遇到一个问题，就是节点的字体有时候不一致，本人没有进行任何特殊设置，莫名的会导致部分节点的字体好像被加粗了，但是确认了也没有被加粗，而且比对了节点样式和普通的样式没有任何的区别，请帮忙看下，
![image](https://github.com/suka233/siyuan-Kmind/assets/16383685/bc5cccb5-ea13-4fec-be99-561c620500fd)

**Comment by Asianfleet** [comment]
我也遇到了同样的问题。希望得到解决

**Comment by suka233** [comment]
已知bug  待解决。。。

**Comment by suka233** [comment]
请更新最新版本
