### ISSUE TITLE
Tab键失灵

### ISSUE THREAD

**Issue by Asianfleet** [suka233/siyuan-Kmind#24]
有的时候选中一个节点之后按tab键不能新建节点
![image](https://github.com/suka233/siyuan-Kmind/assets/88229228/1cfeaf71-2b0b-4a62-9b44-474118bf46fe)

**Comment by suka233** [comment]
你这个是焦点激活到上面的按钮去了，
![image](https://github.com/suka233/siyuan-Kmind/assets/43712875/a1a8282b-ae52-4c7f-b71f-76b9df6b78f7)
重新打开关闭一下该张导图即可，还不行的话就重启一下思源就能解决
