### ISSUE TITLE
就，不能导入？ 很意外

### ISSUE THREAD

**Issue by Sincejunly** [suka233/siyuan-Kmind#6]
![image](https://user-images.githubusercontent.com/96775034/229492959-571e1a6f-8d12-4d3d-a859-cd68032e28d3.png)
看了ban半天能导出不能导入，尬住了

**Comment by suka233** [comment]
emmm，暂时没加这个功能，因为作为一个挂件，往往都是新建导图，所以把导入功能的优先级设置的比较靠后，之后再加吧
