### ISSUE TITLE
界面可以简洁一些嘛

### ISSUE THREAD

**Issue by yylicon** [suka233/siyuan-Kmind#7]
![image](https://user-images.githubusercontent.com/124042427/231638756-d68df69d-cd37-4cfc-882b-002707ca6eb0.png)
嗯，功能很好，很棒。但是做完导图的时候如果能把圈圈这些隐藏掉就好了，比较占地方嗯

**Comment by suka233** [comment]
![image](https://user-images.githubusercontent.com/43712875/231639535-ec9a696e-ecd3-43d0-aeb0-2429e1b0eae4.png)
你好，如果你是在pc端使用，可以右键导图的空白处，然后选择禅模式即可隐藏工具栏
（ps，禅模式的状态也是会跨端同步保存的）

**Comment by yylicon** [comment]
谢谢谢谢，找到了😁
