### ISSUE TITLE
有没有计划增加关联线的功能

### ISSUE THREAD

**Issue by 2524520356** [suka233/siyuan-Kmind#8]
关联线这个功能还挺喜欢的，看原作者有这个功能，不知道思源挂件有没有计划
还有就是键盘上下左右应该是选择&切换节点是吧，有时我要编辑节点内容的时候，想用左右移动文字编辑的光标，但是自动就给我切换到其他节点上了，不知道能不能关闭方向键的快捷键

**Comment by suka233** [comment]
你好，因为最近有点忙，关联线的功能会加上，不过得等一段时间。
键盘方向键和编辑文字冲突已经在v0.1.5被上游库作者解决了，请检查以下你的kmind版本是否大于v0.1.5。
自定义快捷键的功能还没研究过，按理来说是可以办到的。。

**Comment by suka233** [comment]
hello 最新版的kmind已经加上了关联线的功能啦 请更新kmind到最新版使用
