### ISSUE TITLE
New function: fullscreen

### ISSUE THREAD

**Issue by taozina0587** [suka233/siyuan-Kmind#9]
Dude, I really like Kmind. I'm looking for a function but I can't find it. I wanted to ask you to add a new function: full screen. Take all the information off the screen just to leave the mind map. After pressing any icon or pressing any shortcut, the options appeared.

**Comment by suka233** [comment]
Hey there, Do you mean Zen Mode? If so, right click the mind map, then chose this:
![image](https://github.com/suka233/siyuan-Kmind/assets/43712875/e13fa409-d0dd-436b-8c77-3d8677eabcb3)

Make sure your Kmind version is latest
